# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 08:41
from __future__ import unicode_literals

import blog.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100, validators=[blog.validators.MinLengthValidatior(4)], verbose_name='제목')),
                ('content', models.TextField(help_text='Markdown 문법을 써주세요.', validators=[blog.validators.MinLengthValidatior(10)])),
                ('lnglat', models.CharField(help_text='경도,위도 포맷으로 입력', max_length=50, validators=[blog.validators.lnglat_validator])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('text_field', models.IntegerField(default=10)),
                ('post_code', models.CharField(max_length=6, validators=[blog.validators.ZipCodeValidator(True)])),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
